### PR TITLE
Write README

### PR DESCRIPTION
**Pull request by stefanfrede**
@GabrieleRomeo Please have a look if you are ok with the README.

### CODE REVIEW

**Comment by GabrieleRomeo** [comment]
Hi Stefan,
I looked at your README. For me it's ok but, since we're using the BEM technology, I'd like to add some info about it. What do you think?

**Comment by stefanfrede** [comment]
Good idea! I will add some info about BEM.

**Comment by GabrieleRomeo** [comment]
Perfect :+1:

**Comment by stefanfrede** [comment]
@GabrieleRomeo I just refined the README. Please have another look and if you are ok with please merge it into the master. Thanks!

**Comment by GabrieleRomeo** [comment]
Well done!

**Pull request merged**
