### PR TITLE
Improve the look and feel of select dropdowns

### PR DESCRIPTION
**Pull request by stefanfrede**
@GabrieleRomeo What do you think? Now they should look everywhere the same.

### CODE REVIEW

**Comment by GabrieleRomeo** [comment]
**Cool**!! 
Honestly I think that is even **better** of the original one but, as written in the second criteria, to win this contest, we need find the best Design-to-UI Fidelity and, as you can see from the UI design example, **they look different**!

**Comment by stefanfrede** [comment]
Better? Oh, and please don't approve the pull request if you don't, just comment on it without accepting (someone could get tempted to just merge without you being ok with it).

**Comment by GabrieleRomeo** [comment]
Yes better. I like it very much because your version is more harmonious with the rest of the page and it fit much better with other inputs. Isn't it?

**Comment by stefanfrede** [comment]
Yes it does. The `select` element in the design mockups looks like an accident.

**Comment by GabrieleRomeo** [comment]
I fully agree with what you say :+1:

**Pull request merged**
